### ISSUE TITLE
Is This Project Still Alive?

### ISSUE THREAD

**Issue by cctv1005s** [natefinch/lumberjack#159]
Is This Project Still Alive?

**Comment by natefinch** [comment]
The code is stable and free of bugs. It hasn't been under active development mostly because I no longer work on projects that use it. 

I want to make a v3 to clean up the package API, but it's not super high on my list of things to do, since I don't have a ton of free time, and there's not a lot of incentive for me to do it, other than thanks from the community (which I value, but doesn't pay the bills or entertain my kids). 

I am considering setting up a GitHub sponsors page in order to fund development, which would give me more incentive.

**Comment by natefinch** [comment]
Actually I just stared v3 this morning and made a lot of progress. I'll push up the alpha branch soon

**Comment by natefinch** [comment]
There's a v3 branch now that passes all previous tests.  Still needs some cleanup, and probably some of the bugfixes we've been waiting for, but it's a really good start
