### ISSUE TITLE
Multiprocess environment

### ISSUE THREAD

**Issue by Small-World** [natefinch/lumberjack#166]
hello，Does lumberjack support multiple processes, and whether each process needs to use a different file path

**Comment by natefinch** [comment]
It doesn't support multiple processes. Since lumberjack keeps an in-memory record of how large the file is, if you have two processes writing to the same file, it would have an inaccurate record of the size of the file. You can absolutely have two processes writing to two different files, though. And in general I think that's a better solution anyway.

**Comment by Small-World** [comment]
ok，thank you
